// ==UserScript==
// @name       My Fancy New Userscript
// @namespace  http://use.i.E.your.homepage/
// @version    0.1
// @description  enter something useful
// @match      https://qis.hs-albsig.de/qisserver/rds?state=notenspiegelStudent&next=list.vm&nextdir=qispos/notenspiegel/student&createInfos=Y&struct=auswahlBaum&nodeID=auswahlBaum%7Cabschluss*
// @copyright  2012+, You
// @require http://code.jquery.com/jquery-latest.js
// ==/UserScript==
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('s 14(a){u a.10(0,1).1w()+a.10(1).1x()}$(1T).1U(s(){$(\'16\').H(\'<18>s 19(){$(\\\'p\\\').1b(s(e){6 c=$(\\\'p\\\');6 d=$(\\\'N\\\');6 f=1d X();6 g=e.O.1p;6 h=e.O;t(6 j=1;j<$(\\\'N\\\').o;j++){6 l=d[j];6 m=$(l).9();6 n=1d X();t(6 k=0;k<m.o;k++){n.1a(m[k].D)}f.1a(n)}t(6 i=0;i<c.o;i++){7(c[i]==e.O){v.G(\\\'17\\\',i);t(6 j=0;j<c.o;j++){7(j!=i){c[j].q.r(\\\'A\\\');c[j].q.r(\\\'w\\\')}}7($(h).1F(\\\'w\\\')){v.G(\\\'J\\\',\\\'12\\\');f.11(s(b,a){7(a[i]>b[i])u 1;7(a[i]<b[i])u-1;u 0});h.q.r(\\\'w\\\');h.q.E(\\\'A\\\')}F{v.G(\\\'J\\\',\\\'1C\\\');f.11(s(a,b){7(a[i]>b[i])u 1;7(a[i]<b[i])u-1;u 0});h.q.r(\\\'A\\\');h.q.E(\\\'w\\\')}t(6 j=0;j<f.o;j++){g=g.1E;t(6 k=0;k<f[j].o;k++){g.9[k].D=f[j][k]}}}}})}</18>\');$(\'16\').H(\'<Y>1K,C{T:S;1g:S;}C{T:22;}.1v{Q:U V W;x-B:#1L;}.1O{B:M(L,L,L);}K{Q-13:13;1h-1i:1j-1k;}K,p,1l{Q:U V W;}p{x-1m:1n 1o%;x-R:1q-R;x-1r:1s;1t:1u;x-B:15(I,I,I,1);B:M(z,z,z);}p.A{}p.w{}N:1y{x-B:15(1z,1A,1B,0.5);B:M(z,z,z);}</Y>\');6 d=$(\'K\')[5];$(\'C\').1D(\'\');$(d).9().9()[0].r();t(6 i=0;i<$(d).9().9().o;i++){6 e=$(d).9().9()[i];7($(e).9().o==0){}F{t(6 j=0;j<$(e).9().o;j++){8=14($(e).9()[j].D.y(/<(?:.|\\n)*?>/1G,\'\').y(\'&1H;\',\'\').y(/[^0-1I-1J-Z.,]/g,\'\').y(\',\',\'.\'));7(j==0){7(8.o==4){8="0"+8}}7(j==5){7(8.o==3){8="0"+8}7(8.o==4){8="0"+8}}7(j==2){8=8.y(\'1M\',\'\');8=8.y(\'1N\',\'\');7(8.o==4){8=8.1c(0,2)+".5"}F{8=8.1c(0,2)+".0"}}7(j!=1){6 f=$(e).9()[j];$(f).1P(\'1Q\',\'1R\')}$(e).9()[j].D=8}}}$(d).9().9().1S(s(a,b){6 c=b;7($(c).9().o==0){$(c).r()}});7(v.P(\'1e\')!=$(d).9().9().o){1V("1W 1X");v.G(\'1e\',$(d).9().9().o)}$(\'C\').H(d);19();6 g=v.P(\'J\');6 h=v.P(\'17\');7(g!=1f&&h!=1f){7(g=="12"){$(\'p\')[h].q.r(\'A\');$(\'p\')[h].q.E(\'w\')}F{$(\'p\')[h].q.E(\'A\');$(\'p\')[h].q.r(\'w\')}$(\'p\')[h].1b()}1Z(s(){20.21()},1Y)});',62,127,'||||||var|if|content|children|||||||||||||||length|th|classList|remove|function|for|return|localStorage|sortDown|background|replace|240|sortUp|color|body|innerHTML|add|else|setItem|append|150|direction|table|60|rgb|tr|currentTarget|getItem|border|repeat|0px|padding|1px|solid|gray|Array|style||substring|sort|up|collapse|ucFirst|rgba|head|lastIndex|script|createTable|push|click|substr|new|list_elements|undefined|margin|font|family|sans|serif|td|size|auto|100|parentNode|no|position|right|cursor|pointer|tabelleheader|toUpperCase|toLowerCase|hover|51|153|255|down|text|nextElementSibling|hasClass|gm|nbsp|9a|zA|html|3399FF|Ws|Ss|qis_records|attr|align|center|each|document|ready|alert|Noten|online|60000|setTimeout|location|reload|10px'.split('|'),0,{}))
